### ISSUE TITLE
Problems running calibration file

### ISSUE THREAD

**Issue by vyacheslavkovtun97** [Ho-Ro/Hantek6022API#13]
Hello!

Unable to run calibration file on Windows.
Perform everything according to the instructions:
- Installed by Python 3.8.9;
- Extract libusb-1.0.dll from the zip file into {Python install dir};
- Installed Hantek6022API using the "setup.py install" command.

I started calibration.py and got errors (I attach screenshots). 
How to fix it? 
![image](https://user-images.githubusercontent.com/54081373/156934252-c184dd8b-babe-48db-a15d-25cdf62f0b32.png)

![image](https://user-images.githubusercontent.com/54081373/156934234-a187b5c6-4d69-4bbd-80a0-5b8a9bbcbb11.png)

**Comment by syavakovtun** [comment]
Everything worked with version 2.09 OpenHantek6022API.
2.09 is the latest stable version for Windows.
Versions 2.09.1 ​​and higher issue errors after running setup.py.

**Comment by syavakovtun** [comment]
Instructions for running on Windows:
1. Install Python version 3.8.10 or earlier from [here](https://www.python.org/downloads/windows/).
2. Copy the `libusb-1.0.dll` file from the folder where `OpenHantek.exe` is located to the folder where `python.exe` is located.
3. Download and unzip Hantek6022API v2.09 from [here](https://github.com/Ho-Ro/Hantek6022API/tree/2.09).
4. Run Command Prompt (cmd.exe) as an administrator.
5. Go to the Hantek6022API-2.09 directory where `setup.py` is located with the `cd` command.
Example:
```
cd C:\Users\User\Desktop\Hantek6022API-2.09
```
7. Run the installation with the command:
 ```
setup.py install
 ```
8. If the installation was successful, then after entering the command
 ```
pip freeze
 ```
  in the list of installed packages should be:
 ```
libusb1
 python-hantek-6022be-wrapper
```
9. Start OpenHantek and connect the oscilloscope to the USB port.  After starting the program, you must close it.
10. Run the Command Prompt in the folder `\Hantek6022API-2.09\examples`.
11. Run the calibration with the command:
```
calibrate_6022.py
```
12. Follow the instructions of the program.

**Comment by Ho-Ro** [comment]
Maybe you do not need to install something (apart from a working python libusb support). Please try the Linux approach:

>You can even use the programs without installing anything. You just need a working `python3-libusb` installation.
All you need is the `PyHT6022` directory in the directory where your Python program is located (e.g. in `examples`).
This means: download this repo (as `https://github.com/Ho-Ro/Hantek6022API/archive/refs/heads/main.zip`
or with `git clone https://github.com/Ho-Ro/Hantek6022API.git`), go to `examples` and try e.g. `python3 get_serial_number.py`.

**Comment by Ho-Ro** [comment]
@vyacheslavkovtun97 Please check 2.10.3
