### ISSUE TITLE
installation on Windows fails

### ISSUE THREAD

**Issue by Pmant** [Ho-Ro/Hantek6022API#15]
Trying to install this package on Windows fails with `ValueError: path '/usr/bin/' cannot be absolute
`
Probably related to setup.py:
https://github.com/Ho-Ro/Hantek6022API/blob/5d434c2c4a0f1fae250c552629bd12014b6b01b7/setup.py#L30-L45

**Comment by Ho-Ro** [comment]
Please read [my comment](https://github.com/Ho-Ro/Hantek6022API/issues/13#issuecomment-1067043562) to issue #13

**Comment by Pmant** [comment]
Thank for the advice, I did that already and I had no trouble getting things to work. However it makes it hard to integrate the API into other projects as they will always fail to install on windows.

**Comment by Ho-Ro** [comment]
Please try the next version, should not install into absolute path anymore for Windows (which works under Linux). Also the specific Linux related files will not be installed.
