### ISSUE TITLE
pip install fails for non-root user

### ISSUE THREAD

**Issue by lhartmann** [Ho-Ro/Hantek6022API#27]
On debian 12, as non-root user, using venv:

```
$ python3 -m venv /tmp/hantek
$ source /tmp/hantek/bin/activate
$ pip install git+https://github.com/Ho-Ro/Hantek6022API.git
```

fails with
```
error: could not create '/etc/udev/rules.d/60-hantek6022api.rules': Permission denied
```

Installing should not fail, but warn and instruct the user on how to configure the rules.

**Comment by Ho-Ro** [comment]
Please check the latest commit. I'm not using `pip` to install, I use a deb package for clear install/uninstall that can also contain other binaries, libs etc.
Your workflow was never checked.
When using `python setup.py build`, now it excludes the system files and issues a hint how to gain user access, but trying your workflow does not show this message.

**Comment by Ho-Ro** [comment]
I'll close for now, as the pip installation for non-root users is now working as expected. Please comment or reopen if you have an idea on how to display the warning.
Anyway, the README clearly mentions how to use udev rules to gain access to the scope.
