### ISSUE TITLE
build instructions not correct for linux

### ISSUE THREAD

**Issue by bjbeare** [Ho-Ro/Hantek6022API#3]
The instructions have:

=======

You need to compile the custom firmware. Install sdcc for this. Then run make in the directory HantekFirmware/custom:

git submodule update --init
sudo apt-get install sdcc
cd PyHT6022/HantekFirmware/custom
make
Install the python modules and the firmware (e.g. into /usr/local/lib/python3.5/dist-packages/Python-Hantek...).

sudo python3 setup.py install
The provided Makefile simplifies the steps above a little bit

Build the firmware:

make fw_custom
Install modules and firmware:

======

The cd PyHT6022/HantekFirmware/custom directory does not exist. Do you mean custome_BE for the 60222BE?

I was then able to build in custome_BE, but failed with 
sudo python3 setup.py install
I found setup.py in the top level directory (need to add a cd back to the top in the instructions), but the install failed with:

[bjbeare@bjbeare-desktop custom_BE]$ find . -name setup.py
[bjbeare@bjbeare-desktop custom_BE]$ cd -
/home/bjbeare/HanTek/Hantek6022API
[bjbeare@bjbeare-desktop Hantek6022API]$ find . -name setup.py
./setup.py
./PyHT6022/HantekFirmware/fx2lib/examples/fx2/setup.py
[bjbeare@bjbeare-desktop Hantek6022API]$ sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'

**Comment by Ho-Ro** [comment]
Instructions updated: 68822dd 
The custom firmware lives now in custom_BE and (not yet) custom_BL for both HW variants.
There is also a debian package available automatically from each commit: https://ci.appveyor.com/project/Ho-Ro/hantek6022api/build/artifacts

**Comment by Ho-Ro** [comment]
@bjbeare Please check my commit da7dd7b
