### ISSUE TITLE
10bit support

### ISSUE THREAD

**Issue by cbxbiker61** [Ho-Ro/Hantek6022API#4]
Just wondering if you may have an idea how to get this software to support 10bit mode on the 6022.  I see that the Hscope Android app can put the 6022 into a 10bit mode.  It would be particularly nice in the PyQt5 app I'm building. This is an app that does an engine relative compression test using the CC-650 amp clamp.  10bit mode would give my app much better accuracy.

BTW, thanks for supporting the 6022 with Python.  I expect that I'll be using it quite a bit in the future.

**Comment by Ho-Ro** [comment]
Hi, as the analog/digital converter in Hantek6022 is only 8 bit (it's an [AD9288](https://www.analog.com/media/en/technical-documentation/data-sheets/AD9288.pdf)), see also last page of my [User Manual](https://github.com/OpenHantek/OpenHantek6022/blob/master/docs/OpenHantek6022_User_Manual.pdf), I can only think of oversampling to get a better resolution, a trick that I also use in [OpenHantek6022](https://github.com/OpenHantek/OpenHantek6022). Each 4 x oversampling gives 1 bit more of resolution, so 4x -> 9bit, 16x -> 10bit, 64x -> 11 bit, 256x -> 12bit at your choice.

**Comment by cbxbiker61** [comment]
OK, I had already integrated 10x oversampling in the code, since I'm working with low frequency signals and needed to "slow" the signal data down anyway.  I just got a decent trace off my Dodge Ram after I built an adapter with a 0.1uF cap in it to isolate the AC signal and the capture looks useful.
